---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml

namespace: dex
helmGlobals:
  chartHome: ../../charts/

helmCharts:
- name: dex
  includeCRDs: true
  namespace: dex
  valuesFile: values.yaml
  releaseName: dex
  version: 0.16.0
  repo: https://charts.dexidp.io
