---
apiVersion: mariadb.mmontes.io/v1alpha1
kind: MariaDB
metadata:
  name: mariadb  # this name is referenced by other resource kinds
spec:
  rootPasswordSecretKeyRef:
    name: mariadb
    key: root-password

  image: mariadb:11.0.3
  imagePullPolicy: IfNotPresent

  port: 3306
  volumeClaimTemplate:
    resources:
      requests:
        storage: 1Gi
    accessModes:
      - ReadWriteOnce

  service:
    type: ClusterIP

  myCnf: |
    [mariadb]
    bind-address=*
    default_storage_engine=InnoDB
    binlog_format=row
    innodb_autoinc_lock_mode=2
    max_allowed_packet=256M

  metrics:
    enabled: true
