apiVersion: argoproj.io/v1alpha1
metadata:
  name: synchronize-provision-state-to-nautobot
kind: WorkflowTemplate
spec:
  serviceAccountName: workflow
  templates:
    - name: synchronize-state
      container:
        image: ghcr.io/rackerlabs/understack/ironic-nautobot-client:latest
        command:
          - nautobot-update-cf
        args:
          - --device-id
          - "{{workflow.parameters.device_uuid}}"
          - --field-name
          - "ironic_provisioning_status"
          - --field-value
          - "{{workflow.parameters.provision_state}}"
        volumeMounts:
          - mountPath: /etc/nb-token/
            name: nb-token
            readOnly: true
      inputs:
        parameters:
          - name: device_uuid
          - name: provision_state
      volumes:
        - name: nb-token
          secret:
            secretName: nautobot-token
