[files]
extend-exclude = [
    ".venv",
    "venv",
    "assets",
    "schema/argo-workflows.json",
]

[default]
extend-ignore-identifiers-re = [
    "ironic_retrive_*",
]

[default.extend-words]
# Don't correct "HPE"
HPE = "HPE"
