---
site_name: Understack
site_description: |-
  Understack is a collection of open-source tools and technologies that provides
  flexible, scalable, and cost-effective infrastructure management solution. The
  focus is on deploying bare metal in data centers with functional DCIM and IPAM.

theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/logo.png
  favicon: assets/favicon.png

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

  features:
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.instant
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - toc.follow

repo_name: rackerlabs/understack
repo_url: https://github.com/rackerlabs/understack
dev_addr: "127.0.0.1:8001"
edit_uri: "edit/main/docs"

copyright: Copyright &copy; 2024 Rackspace Technology, Inc.

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
  anchors: warn

nav:
  - Home: index.md
  - Overview:
    - vision.md
    - 'Prerequisites':
      - kubernetes.md
      - openstack-helm.md
    - 'Configuration':
      - secrets.md
      - networking.md
    - Components:
      - component-overview.md
      - component-argo-events.md
      - component-argo-workflows.md
  - 'Deployment Guide':
    - deploy-guide/index.md
    - deploy-guide/gitops-install.md
    - deploy-guide/install-understack-ubuntu-k3s.md
    - deploy-guide/auth.md
  - 'User Guide':
    - user-guide/index.md
    - user-guide/openstack-cli.md
