---
# Source: nautobot/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nautobot
  namespace: "nautobot"
  labels:
    app.kubernetes.io/name: nautobot
    helm.sh/chart: nautobot-2.0.5
    app.kubernetes.io/instance: nautobot
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: "2.0.5"
automountServiceAccountToken: false
