apiVersion: argoproj.io/v1alpha1
metadata:
  name: sync-server-to-ironic
  annotations:
    workflows.argoproj.io/description: |
      Defined in `argo-workflows/sync-nb-server-to-ironic/sync-server-to-ironic.yaml`
kind: WorkflowTemplate
spec:
  arguments:
    parameters:
      - name: interface_update_event
        value: "{}"
  templates:
    - name: main
      input:
        parameters:
          - name: interface_update_event
      output:
        parameters:
          - name: server_state
            valueFrom:
              expression: "{{ steps.sync-server.outputs.parameters.result }}"
      steps:
        - - name: sync-server
            container:
            image: ghcr.io/rackerlabs/understack/ironic-nautobot-client:latest
            command:
              - sync-server
            args:
              - "{{input.parameters.interface_update_event}}"
            volumeMounts:
              - mountPath: /etc/ironic-secrets/
                name: ironic-secrets
                readOnly: true
            volumes:
              - name: ironic-secrets
                secret:
                secretName: production-ironic-for-argo-creds
