---

nautobot:
  image:
    tag: "2.1.1-py3.11"

  db:
    engine: "django.db.backends.postgresql"
    host: "nautobot-primary.nautobot.svc"
    name: "nautobot"
    user: "nautobot"
    existingSecret: "nautobot-pguser-nautobot"
    existingSecretPasswordKey: "password"

  redis:
    host: "nautobot-redis-master"
    existingSecret: "nautobot-redis"
    existingSecretPasswordKey: "redis-password"

celery:
  replicaCount: 1

postgresql:
  enabled: false

redis:
  enabled: false

ingress:
  enabled: true
  ingressClassName: "nginx"
  tls: true
  secretName: "nautobot-ingress-tls"
  annotations:
    cert-manager.io/cluster-issuer: selfsigned-cluster-issuer
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
