apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openstack

resources:
  - eventbus-default.yaml
  - eventsource-openstack-ironic.yaml
  - eventsource-openstack-keystone.yaml
  - poddisruptionbudget-eventbus-default-pdb.yaml
  - rabbitmq-permission-argo-to-ironic-permission.yaml
  - rabbitmq-permission-argo-to-keystone-permission.yaml
  - rabbitmq-user-argo.yaml
  - sensor-keystone-event-project.yaml
  - serviceaccount-sensor-submit-workflow.yaml
