apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: debug-sensor
  namespace: argo-events
spec:
  dependencies:
  - eventName: interface-update
    eventSourceName: selfproduced
    name: interface-update
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
  - template:
      log: {}
      name: debug-trigger
