apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  finalizers:
  - sensor-controller
  labels:
    argocd.argoproj.io/instance: argo-events
  name: nautobot-interface-update
  namespace: argo-events
spec:
  dependencies:
  - eventName: nautobot
    eventSourceName: nautobot-webhook
    name: nautobot-dep
    filters:
      dataLogicalOperator: "and"
      data:
        - path: "body.event"
          type: "string"
          value:
            - "updated"
        - path: "body.model"
          type: "string"
          value:
            - "interface"
        - path: "body.data.name"
          type: "string"
          value:
            - "iLO"
            - "iDRAC"
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
  - template:
      k8s:
        operation: create
        parameters:
        - dest: spec.arguments.parameters.0.value
          src:
            dataKey: body
            dependencyName: nautobot-dep
        source:
          resource:
            apiVersion: argoproj.io/v1alpha1
            kind: Workflow
            metadata:
              generateName: nautobot-interface-update-
            spec:
              entrypoint: start
              arguments:
                parameters:
                  - name: message
                    value: "Some nautobot interface has changed"
              templates:
                - name: start
                  container:
                    image: docker/whalesay:latest
                    command:
                      - cowsay
                    args:
                      - 'Some nautobot interface has changed'
      name: nautobot-interface-update-trigger
