apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-config
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-cluster-config'
    spec:
      project: default
      sources:
        - repoURL: '{{index .metadata.annotations "uc_deploy_git_url"}}'
          path: secrets/{{.name}}/cluster/
          targetRevision: '{{index .metadata.annotations "uc_deploy_ref"}}'
      ignoreDifferences:
        - kind: Secret
          namespace: argocd
          jqPathExpressions:
            - .metadata.annotations.uc_repo_ref
            - .metadata.annotations.uc_deploy_ref
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - RespectIgnoreDifferences=true
