apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-events
spec:
  project: understack
  source:
    repoURL: https://github.com/rackerlabs/understack.git
    path: components/12-argo-events/
    targetRevision: ${UC_REPO_REF}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-events
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
