apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
spec:
  project: understack
  source:
    repoURL: https://github.com/rackerlabs/understack.git
    path: components/11-argo-workflows/
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    automated:
      selfHeal: true
