apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows-templates
spec:
  project: understack
  sources:
    - repoURL: https://github.com/rackerlabs/understack.git
      path: argo-workflows/
      targetRevision: ${UC_REPO_REF}
      directory:
        recurse: true
        include: '{*/deps/*.yaml,*/sensors/*.yaml,*/workflowtemplates/*.yaml}'
        exclude: '{example-feature/*,*/*/*example*}'
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: argo-workflows/
      targetRevision: ${UC_DEPLOY_REF}
      directory:
        recurse: true
        include: '{*/deps/*.yaml,*/sensors/*.yaml,*/workflowtemplates/*.yaml}'
        exclude: '*/*/*example*'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo-events
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
