apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dexidp
spec:
  project: understack
  sources:
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/13-dexidp/
      targetRevision: HEAD
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: secrets/${DEPLOY_NAME}/
      targetRevision: HEAD
      directory:
        include: secret-nautobot-sso-dex.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dex
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
