apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dexidp
spec:
  project: understack
  sources:
    - chart: dex
      repoURL: https://charts.dexidp.io
      targetRevision: 0.16.0
      helm:
        releaseName: dex
        valueFiles:
          - $values/components/dexidp/values-generic.yaml
          - $secrets/helm-configs/${DEPLOY_NAME}/dexidp.yaml
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/dexidp
      targetRevision: ${UC_REPO_REF}
      ref: values
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: secrets/${DEPLOY_NAME}/
      targetRevision: HEAD
      directory:
        include: secret-nautobot-sso-dex.yaml
      ref: secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: dex
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
