apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keystone
spec:
  project: understack
  sources:
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/10-keystone/
      targetRevision: ${UC_REPO_REF}
      directory:
        exclude: kustomization.yaml
        recurse: false
      ref: understack
    - repoURL: https://tarballs.opendev.org/openstack/openstack-helm/
      chart: keystone
      targetRevision: 0.3.7
      helm:
        releaseName: keystone
        valueFiles:
          - $understack/components/openstack-2023.1-jammy.yaml
          - $understack/components/10-keystone/aio-values.yaml
          - $secrets/secrets/${DEPLOY_NAME}/secret-openstack.yaml
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: secrets/${DEPLOY_NAME}/
      targetRevision: HEAD
      directory:
        include: 'secret-keystone-*.yaml'
      ref: secrets
  ignoreDifferences:
    - kind: Secret
      name: keystone-fernet-keys
      jqPathExpressions:
        - .data
    - kind: Secret
      name: keystone-credential-keys
      jqPathExpressions:
        - .data
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openstack
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        kubernetes.io/metadata.name: openstack
        name: openstack
