apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keystone
spec:
  project: understack
  source:
    repoURL: https://github.com/rackerlabs/understack.git
    path: components/10-keystone/
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openstack
  syncPolicy:
    automated:
      selfHeal: true
