apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautobot
spec:
  project: understack
  sources:
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/08-nautobot-redis/
      targetRevision: HEAD
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/09-nautobot/
      targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nautobot
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
