apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nautobot-redis
spec:
  project: understack
  source:
    repoURL: https://github.com/rackerlabs/understack.git
    path: components/08-nautobot-redis/
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nautobot
  syncPolicy:
    automated:
      selfHeal: true
