apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openstack-admin-client
spec:
  project: understack
  sources:
    - repoURL: https://github.com/rackerlabs/understack.git
      path: components/openstack-admin-client/
      targetRevision: ${UC_REPO_REF}
      ref: understack
  destination:
    server: "https://kubernetes.default.svc"
    namespace: openstack
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    managedNamespaceMetadata:
      labels:
        kubernetes.io/metadata.name: openstack
        name: openstack
