apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-db
spec:
  project: understack
  source:
    repoURL: https://github.com/rackerlabs/understack.git
    path: components/07-postgres/
    targetRevision: ${UC_REPO_REF}
  destination:
    server: "https://kubernetes.default.svc"
    namespace: nautobot
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
