apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: undersync
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-undersync'
    spec:
      project: default
      source:
        repoURL: '{{index .metadata.annotations "uc_repo_git_url"}}'
        targetRevision: '{{index .metadata.annotations "uc_repo_ref"}}'
        path: 'components/undersync'
      destination:
        server: '{{.server}}'
        namespace: 'undersync'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
