apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  finalizers:
  - sensor-controller
  labels:
    argocd.argoproj.io/instance: argo-events
  name: nautobot-interface-update-int-sync
  namespace: argo-events
spec:
  dependencies:
  - eventName: nautobot
    eventSourceName: nautobot-webhook
    name: nautobot-dep
    filters:
      dataLogicalOperator: "and"
      data:
        - path: "body.event"
          type: "string"
          value:
            - "updated"
        - path: "body.model"
          type: "string"
          value:
            - "interface"
        - path: body.data.name
          type: string
          value:
            - iLO
            - iDRAC
        - path: body.data.ip_addresses.0
          type: string
          value:
            - .*
  template:
    serviceAccountName: operate-workflow-sa
  triggers:
    - template:
        name: nautobot-interface-int-sync-update-trigger
        k8s:
          operation: create
          parameters:
            - dest: spec.arguments.parameters.0.value
              src:
                dataKey: body.data.device.name
                dependencyName: nautobot-dep
          source:
            resource:
              apiVersion: argoproj.io/v1alpha1
              kind: Workflow
              metadata:
                generateName: nautobot-interface-sync-
              spec:
                arguments:
                  parameters:
                    - name: hostname
                      value: Nautobot device hostname
                entrypoint: start
                serviceAccountName: workflow
                templates:
                  - name: start
                    steps:
                      - - name: get-obm-creds-secret
                          templateRef:
                            name: get-obm-creds
                            template: main
                          arguments:
                            parameters:
                              - name: hostname
                                value: "{{workflow.parameters.hostname}}"
                      - - name: synchronize-interfaces-to-nautobot
                          templateRef:
                            name: synchronize-interfaces-to-nautobot
                            template: synchronize-interfaces
                          arguments:
                            parameters:
                              - name: hostname
                                value: "{{workflow.parameters.hostname}}"
                              - name: oob_secret
                                value: "{{steps.get-obm-creds-secret.outputs.parameters.secret}}"
