apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/rabbitmq/cluster-operator/releases/latest/download/cluster-operator.yml

# this needs to be here to remove the namespace from the above
# because the messaging-topology-operator defines the same namespace and it would conflict
patches:
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: rabbitmq-system
    $patch: delete

# have to put this after the patch above
resources:  # yamllint disable-line rule:key-duplicates
  - https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.13.0/messaging-topology-operator-with-certmanager.yaml
