apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- nautobot/templates/celery-deployment.yaml
- nautobot/templates/configmap.yaml
- nautobot/templates/nautobot-deployment.yaml
- nautobot/templates/nginx-configmap.yaml
- nautobot/templates/service-account.yaml
- nautobot/templates/service.yaml
- nautobot/templates/ingress.yaml
