---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nautobot-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dex
  target:
    name: nautobot-sso
    creationPolicy: Owner
    deletionPolicy: Delete
    template:
      engineVersion: v2
      data:
        # need to re-generate secrets first
        # client-id: "{{ .client_id }}"
        client-secret: "{{ .client_secret }}"
  data:
  - secretKey: client_secret
    remoteRef:
      key: nautobot-sso
      property: client-secret
