---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-nautobot.yaml
  - secretstore-nautobot.yaml

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 18.12.1
  namespace: nautobot
  releaseName: nautobot-redis
  valuesFile: redis-values.yaml
