---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres-nautobot.yaml
  - secretstore-nautobot.yaml
  - external-secret-nautobot-sso.yaml

configMapGenerator:
  - name: dexauth
    files:
      - dexauth.py
    options:
      disableNameSuffixHash: true

helmCharts:
- name: redis
  repo: https://charts.bitnami.com/bitnami
  version: 18.19.4
  namespace: nautobot
  releaseName: nautobot
  valuesFile: redis-values.yaml
