auth:
  existingSecret: nautobot-redis
  existingSecretPasswordKey: redis-password

architecture: "standalone"

image:
  pullPolicy: "Always"
master:
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - "ALL"
  disableCommands: []
  podSecurityContext:
    seccompProfile:
      type: "RuntimeDefault"
metrics:
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - "ALL"
replica:
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    capabilities:
      drop:
        - "ALL"
  disableCommands: []
  podSecurityContext:
    seccompProfile:
      type: "RuntimeDefault"
sentinel:
  containerSecurityContext:
    enabled: true
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    capabilities:
      drop:
        - "ALL"
  podSecurityContext:
    seccompProfile:
      type: "RuntimeDefault"
serviceAccount:
  automountServiceAccountToken: false
