# add your values.yaml overrides for the helm chart here

ingress:
  annotations:
    cert-manager.io/cluster-issuer: ${DEPLOY_NAME}-cluster-issuer
    nginx.ingress.kubernetes.io/backend-protocol: HTTPS
  hostname: nautobot.${DNS_ZONE}

nautobot:
  extraEnvVars:
    - name: SOCIAL_AUTH_OIDC_OIDC_ENDPOINT
      value: https://dex.${DNS_ZONE}
