---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bmc-sync-creds
  namespace: argo-events
  annotations:
    workflows.argoproj.io/title: Sync's a devices BMC password with what we have on record
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/bmc-sync-creds.yaml`
spec:
  arguments:
    parameters:
      - name: device_id
  serviceAccountName: workflow
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: get-bmc-ip
            templateRef:
              name: get-bmc-ip
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
          - name: get-bmc-creds
            templateRef:
              name: get-bmc-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
          - name: bmc-sync-creds
            dependencies: [get-bmc-ip, get-bmc-creds]
            template: bmc-sync-creds
            arguments:
              parameters:
                - name: host
                  value: "{{tasks.get-bmc-ip.outputs.parameters.ip}}"
                - name: target_creds_secret_name
                  value: "{{tasks.get-bmc-creds.outputs.parameters.secret}}"
          - name: idrac-enable-network-boot
            dependencies: [get-bmc-ip, get-bmc-creds]
            templateRef:
              name: idrac-enable-network-boot
              template: idrac-enable-network-boot
            arguments:
              parameters:
                - name: host
                  value: "{{tasks.get-bmc-ip.outputs.parameters.ip}}"
                - name: target_creds_secret_name
                  value: "{{tasks.get-bmc-creds.outputs.parameters.secret}}"

    - name: bmc-sync-creds
      inputs:
        parameters:
          - name: host
          - name: target_creds_secret_name
      container:
        image: ghcr.io/rackerlabs/understack/argo-bmc-utils-python3.11.8:latest
        command: [python]
        args: ["/app/bmc_sync_creds.py", "--host", "{{ inputs.parameters.host }}"]
        env:
          - name: BMC_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{inputs.parameters.target_creds_secret_name}}"
                key: username
          - name: BMC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{inputs.parameters.target_creds_secret_name}}"
                key: password
          - name: BMC_LEGACY_PASSWORDS
            valueFrom:
              secretKeyRef:
                name: bmc-legacy-passwords
                key: passwords
