apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: bmc-firmware-update
  namespace: argo-events
  annotations:
    workflows.argoproj.io/title: Update BMC firmware on target Device
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/bmc-firmware-update.yaml`
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: device_id
      - name: firmware-url
  templates:
    - name: main
      dag:
        tasks:
          - name: get-bmc-ip
            templateRef:
              name: get-bmc-ip
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
          - name: get-bmc-creds
            templateRef:
              name: get-bmc-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
          - name: update-firmware
            dependencies: [get-bmc-ip, get-bmc-creds]
            template: bmc-firmware-update
            arguments:
              parameters:
                - name: ip
                  value: "{{tasks.get-bmc-ip.outputs.parameters.ip}}"
                - name: creds
                  value: "{{tasks.get-bmc-creds.outputs.parameters.secret}}"
                - name: firmware_url
                  value: "{{workflow.parameters.firmware-url}}"

    - name: bmc-firmware-update
      inputs:
        parameters:
          - name: ip
          - name: creds
          - name: firmware_url
      container:
        image: ghcr.io/rackerlabs/understack/argo-bmc-utils-python3.11.8:latest
        command: [python]
        args: ["/app/bmc_firmware_update.py", "--host", "{{inputs.parameters.ip}}", "--firmware-url", "{{inputs.parameters.firmware_url}}"]
        env:
        - name: BMC_USERNAME
          valueFrom:
            secretKeyRef:
              name: "{{inputs.parameters.creds}}"
              key: username
        - name: BMC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: "{{inputs.parameters.creds}}"
              key: password
