apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-obm-ip
  namespace: argo-events
  annotations:
    workflows.argoproj.io/title: Output OBM IP address for the Device with the given device_id
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/get-obm-ip.yaml`.
      Get OBM IP address for target Device
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: device_id
  templates:
    - name: main
      inputs:
        parameters:
          - name: device_id
      outputs:
        parameters:
          - name: ip
            valueFrom:
              expression: "jsonpath(steps['nautobot-query'].outputs.parameters.result, '$.results.[0].host')"
      steps:
        - - name: nautobot-query
            templateRef:
              name: nautobot-api
              template: main
            arguments:
              parameters:
                - name: uri
                  value: "/ipam/ip-addresses/?device_id={{inputs.parameters.device_id}}&interfaces=iDRAC&interfaces=iLO"
