---
apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: idrac-enable-network-boot
  namespace: argo-events
  annotations:
    workflows.argoproj.io/title: Enable network boot in Dell iDrac BIOS
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/idrac-enable-network-boot.yaml`
spec:
  arguments:
    parameters:
      - name: device_id
  serviceAccountName: workflow
  entrypoint: main
  templates:
    - name: main
      dag:
        tasks:
          - name: get-bmc-ip
            templateRef:
              name: get-bmc-ip
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
          - name: get-bmc-creds
            templateRef:
              name: get-bmc-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
          - name: idrac-enable-network-boot
            dependencies: [get-bmc-ip, get-bmc-creds]
            template: idrac-enable-network-boot
            arguments:
              parameters:
                - name: host
                  value: "{{tasks.get-bmc-ip.outputs.parameters.ip}}"
                - name: target_creds_secret_name
                  value: "{{tasks.get-bmc-creds.outputs.parameters.secret}}"

    - name: idrac-enable-network-boot
      inputs:
        parameters:
          - name: host
          - name: target_creds_secret_name
      container:
        image: ghcr.io/rackerlabs/understack/argo-bmc-utils-python3.11.8:latest
        command: [GetSetBiosAttributesREDFISH.py]
        args: ["-ip", "{{ inputs.parameters.host }}", "-u", "$BMC_USERNAME", "-p", "$BMC_PASSWORD", "--attribute-names", "PxeDev1EnDis,PxeDev1Interface,HttpDev1Interface", "--attribute-values", "Enabled,NIC.Slot.1-1,NIC.Slot.1-1", "--reboot"]
        env:
          - name: BMC_USERNAME
            valueFrom:
              secretKeyRef:
                name: "{{inputs.parameters.target_creds_secret_name}}"
                key: username
          - name: BMC_PASSWORD
            valueFrom:
              secretKeyRef:
                name: "{{inputs.parameters.target_creds_secret_name}}"
                key: password
