apiVersion: argoproj.io/v1alpha1
metadata:
  name: sync-system-info-to-nautobot
  annotations:
    workflows.argoproj.io/title: Sync Redfish system info (serial number, service tag, model name) data to Nautobot
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/sync-system-info-to-nautobot.yaml`
kind: WorkflowTemplate
spec:
  arguments:
    parameters:
      - name: device_id
        value: "{}"
      - name: bmc_secret
        value: "{}"
  templates:
    - name: sync-system-info
      container:
        image: ghcr.io/rackerlabs/understack/ironic-nautobot-client:latest
        command:
          - sync-nautobot-system-info
        args: ["--device-id", "{{workflow.parameters.device_id}}"]
        volumeMounts:
          - mountPath: /etc/nb-token/
            name: nb-token
            readOnly: true
          - mountPath: /etc/bmc-secrets/
            name: bmc-secrets
            readOnly: true
      inputs:
        parameters:
          - name: bmc_secret
      volumes:
        - name: nb-token
          secret:
            secretName: nautobot-token
        - name: bmc-secrets
          secret:
            secretName: "{{inputs.parameters.bmc_secret}}"
