apiVersion: argoproj.io/v1alpha1
metadata:
  name: sync-obm-creds
  annotations:
    workflows.argoproj.io/title: Update a Device's BMC (redfish) username/password in Ironic
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/sync-obm-creds.yaml`
kind: WorkflowTemplate
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: interface_update_event
        value: "{}"
  templates:
    - name: main
      steps:
        - - name: load-obm-creds
            templateRef:
              name: get-obm-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: '{{workflow.parameters.device_id}}'
        - - name: sync-obm-creds
            template: sync-obm-creds
            arguments:
              parameters:
                - name: obm
                  value: "{{ steps.load-obm-creds.outputs.parameters.secret }}"

    - name: sync-obm-creds
      inputs:
        parameters:
          - name: obm
      container:
        image: ghcr.io/rackerlabs/understack/ironic-nautobot-client:latest
        command:
          - sync-obm-creds
        args:
          - "{{workflow.parameters.interface_update_event}}"
        volumeMounts:
          - mountPath: /etc/openstack
            name: openstack-svc-acct
            readOnly: true
          - mountPath: /etc/ironic-secrets/
            name: ironic-secrets
            readOnly: true
          - mountPath: /etc/obm
            name: obm-secret
            readOnly: true
      volumes:
        - name: openstack-svc-acct
          secret:
            secretName: openstack-svc-acct
        - name: ironic-secrets
          secret:
            secretName: production-ironic-for-argo-creds
        - name: obm-secret
          secret:
            secretName: "{{ inputs.parameters.obm }}"
