apiVersion: argoproj.io/v1alpha1
metadata:
  name: sync-bmc-creds
  annotations:
    workflows.argoproj.io/title: Update a Device's BMC (redfish) username/password in Ironic
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/sync-bmc-creds.yaml`
kind: WorkflowTemplate
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: interface_update_event
        value: "{}"
  templates:
    - name: main
      steps:
        - - name: load-bmc-creds
            templateRef:
              name: get-bmc-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: '{{workflow.parameters.device_id}}'
        - - name: sync-bmc-creds
            template: sync-bmc-creds
            arguments:
              parameters:
                - name: bmc
                  value: "{{ steps.load-bmc-creds.outputs.parameters.secret }}"

    - name: sync-bmc-creds
      inputs:
        parameters:
          - name: bmc
      container:
        image: ghcr.io/rackerlabs/understack/ironic-nautobot-client:latest
        command:
          - sync-bmc-creds
        args:
          - "{{workflow.parameters.interface_update_event}}"
        volumeMounts:
          - mountPath: /etc/openstack
            name: openstack-svc-acct
            readOnly: true
          - mountPath: /etc/bmc
            name: bmc-secret
            readOnly: true
      volumes:
        - name: openstack-svc-acct
          secret:
            secretName: openstack-svc-acct
        - name: bmc-secret
          secret:
            secretName: "{{ inputs.parameters.bmc }}"
