apiVersion: argoproj.io/v1alpha1
metadata:
  name: sync-srv-redfish-intfs-to-nb
  annotations:
    workflows.argoproj.io/title: Sync Redfish interface data to Nautobot
    workflows.argoproj.io/description: |
      Defined in `workflows/argo-events/workflowtemplates/sync-srv-redfish-intfs-to-nb.yaml`
kind: WorkflowTemplate
spec:
  entrypoint: main
  arguments:
    parameters:
      - name: device_id
        value: "{}"
  templates:
    - name: main
      steps:
        - - name: sync-bmc-creds-to-server
            templateRef:
              name: bmc-sync-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
        - - name: get-bmc-creds-secret
            templateRef:
              name: get-bmc-creds
              template: main
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
        - - name: sync-interfaces-to-nautobot
            templateRef:
              name: sync-interfaces-to-nautobot
              template: sync-interfaces
            arguments:
              parameters:
                - name: device_id
                  value: "{{workflow.parameters.device_id}}"
                - name: oob_secret
                  value: "{{steps.get-bmc-creds-secret.outputs.parameters.secret}}"
