---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts/
helmCharts:
- name: redis
  includeCRDs: true
  namespace: nautobot
  valuesFile: values.yaml
  releaseName: nautobot-redis
  version: 18.12.1
  repo: https://charts.bitnami.com/bitnami
