---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - mariadb-configmap.yaml
  - mariadb-instance.yaml
  - openstack-cluster.yaml

helmCharts:
  - name: memcached
    repo: https://charts.bitnami.com/bitnami
    version: 6.7.1
    releaseName: memcached
    valuesFile: memcached-values.yaml
