# add your values.yaml overrides for the helm chart here

network:
  api:
    ingress:
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
        cert-manager.io/cluster-issuer: ${DEPLOY_NAME}-cluster-issuer
