---
apiVersion: rabbitmq.com/v1beta1
kind: User
metadata:
  name: argo
spec:
  rabbitmqClusterReference:
    name: rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
    namespace: openstack
---
apiVersion: rabbitmq.com/v1beta1
kind: Permission
metadata:
  name: argo-to-ironic-permission
spec:
  vhost: "ironic"
  userReference:
    name: "argo"  # name of a user.rabbitmq.com in the same namespace; must specify either spec.userReference or spec.user
  permissions:
    write: "^$"
    configure: "^$"
    read: "^ironic_versioned_notifications.info$"
  rabbitmqClusterReference:
    name: rabbitmq  # rabbitmqCluster must exist in the same namespace as this resource
    namespace: openstack
