apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/CrunchyData/postgres-operator-examples.git//kustomize/install/namespace/?ref=main
  - https://github.com/CrunchyData/postgres-operator-examples.git//kustomize/install/default/?ref=main

patches:
- patch: |-
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: pgo
    spec:
      template:
        spec:
          containers:
          - name: operator
            env:
            - name: CRUNCHY_DEBUG
              value: "false"
