apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cert-manager
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-cert-manager'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      sources:
        - repoURL: https://charts.jetstack.io
          chart: cert-manager
          targetRevision: '1.*'
          helm:
            releaseName: cert-manager
            valuesObject:
              installCRDs: true
        - repoURL: '{{index .metadata.annotations "uc_deploy_git_url"}}'
          path: secrets/{{.name}}/
          targetRevision: '{{index .metadata.annotations "uc_deploy_ref"}}'
          directory:
            include: 'secret-acme-*.yaml'
          ref: secrets
      destination:
        server: '{{.server}}'
        namespace: cert-manager
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
