apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: components
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
    applicationsSync: create-update
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - list:
              elements:
                - component: openstack
                - component: undersync
  template:
    metadata:
      name: '{{.name}}-{{.component}}'
    spec:
      project: default
      source:
        repoURL: '{{index .metadata.annotations "uc_repo_git_url"}}'
        targetRevision: '{{index .metadata.annotations "uc_repo_ref"}}'
        path: 'components/{{.component}}'
      destination:
        server: '{{.server}}'
        namespace: '{{.component}}'
      syncPolicy:
        automated:
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
