apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - matrix:
        generators:
          - clusters:
              selector:
                matchLabels:
                  argocd.argoproj.io/secret-type: cluster
          - list:
              elements:
                - component: cert-manager
                  source:
                    repoURL: https://charts.jetstack.io
                    chart: cert-manager
                    targetRevision: '1.*'
                    helm:
                      releaseName: cert-manager
                      valuesObject:
                        installCRDs: true
                - component: ingress-nginx
                  sources:
                    - repoURL: '{{index .metadata.annotations "uc_deploy_git_url"}}'
                      targetRevision: '{{index .metadata.annotations "uc_deploy_ref"}}'
                      ref: secrets
                    - repoURL: https://kubernetes.github.io/ingress-nginx
                      chart: ingress-nginx
                      targetRevision: 4.9.1
                      helm:
                        releaseName: ingress-nginx
                        valueFiles:
                          - $secrets/helm-configs/{{.name}}/ingress-nginx.yaml
                        ignoreMissingValueFiles: true
                    - repoURL: https://kubernetes.github.io/ingress-nginx
                      chart: ingress-nginx
                      targetRevision: 4.9.1
                      helm:
                        releaseName: provisioning-ingress-nginx
                        valuesObject:
                          controller:
                            electionID: ingress-controller-leader
                            ingressClass: provisioning-nginx  # default: nginx
                            ingressClassResource:
                              name: provisioning-nginx  # default: nginx
                              enabled: true
                              default: false
                              controllerValue: "k8s.io/provisioning-ingress-nginx"  # default: k8s.io/ingress-nginx
                        valueFiles:
                          - $secrets/helm-configs/{{.name}}/provisioning-ingress-nginx.yaml
                        ignoreMissingValueFiles: true
  template:
    metadata:
      name: '{{.name}}-{{.component}}'
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: default
      destination:
        server: '{{.server}}'
        namespace: '{{.component}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      {{- if hasKey . "source" }}
      # indentation matters so collapse to single line with toJson to keep it
      source: {{ .source | toJson }}
      {{- end }}
      {{- if hasKey . "sources" }}
      sources:
        {{- range $source := .sources }}
        # indentation matters so collapse to single line with toJson to keep it
        - {{ $source | toJson }}
        {{- end }}
      {{- end }}
