apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: uc-workflows
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-uc-workflows'
    spec:
      project: default
      sources:
        - repoURL: '{{index .metadata.annotations "uc_repo_git_url"}}'
          targetRevision: '{{index .metadata.annotations "uc_repo_ref"}}'
          path: 'argo-workflows'
          directory:
            recurse: true
            include: '{shared-sensors/*.yaml,*/deps/*.yaml,*/sensors/*.yaml,*/workflowtemplates/*.yaml}'
            exclude: '{example-feature/*,*/*/*example*}'
        - repoURL: '{{index .metadata.annotations "uc_deploy_git_url"}}'
          targetRevision: '{{index .metadata.annotations "uc_deploy_ref"}}'
          path: 'argo-workflows'
          directory:
            recurse: true
            include: '{*/deps/*.yaml,*/sensors/*.yaml,*/workflowtemplates/*.yaml}'
            exclude: '*/*/*example*'
      destination:
        server: '{{.server}}'
        namespace: argo-events
      syncPolicy:
        automated:
          selfHeal: true
