---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: operators
  sources:
    - chart: cert-manager
      repoURL: https://charts.jetstack.io
      targetRevision: 1.*
      helm:
        releaseName: cert-manager
        valuesObject:
          installCRDs: true
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: secrets/${DEPLOY_NAME}/
      targetRevision: ${UC_DEPLOY_REF}
      directory:
        include: cluster-issuer.yaml
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
