apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
spec:
  project: operators
  sources:
    - chart: ingress-nginx
      repoURL: https://kubernetes.github.io/ingress-nginx
      targetRevision: 4.9.1
      helm:
        releaseName: ingress-nginx
        valueFiles:
          - $values/bootstrap/phase_2/ingress-nginx/values.yaml
          - $secrets/helm-configs/${DEPLOY_NAME}/ingress-nginx.yaml
    - repoURL: https://github.com/rackerlabs/understack.git
      targetRevision: ${UC_REPO_REF}
      ref: values
    - repoURL: ${UC_DEPLOY_GIT_URL}
      targetRevision: HEAD
      ref: secrets
  destination:
    server: "https://kubernetes.default.svc"
    namespace: ingress-nginx
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
