apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
spec:
  project: operators
  sources:
    - repoURL: https://github.com/rackerlabs/understack.git
      path: bootstrap/metallb
      targetRevision: ${UC_REPO_REF}
    - repoURL: ${UC_DEPLOY_GIT_URL}
      path: secrets/${DEPLOY_NAME}/
      targetRevision: ${UC_DEPLOY_REF}
      directory:
        include: 'secret-metallb*.yaml'
  destination:
    server: "https://kubernetes.default.svc"
    namespace: metallb-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: bgppeers.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
  - group: "apiextensions.k8s.io"
    kind: CustomResourceDefinition
    name: addresspools.metallb.io
    jsonPointers:
    - /spec/conversion/webhook/clientConfig/caBundle
