apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq-operator
spec:
  project: operators
  source:
    repoURL: https://github.com/rackerlabs/understack.git
    path: operators/rabbitmq-operator/
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: rabbitmq-system
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
