apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-setup
spec:
  syncPolicy:
    preserveResourcesOnDeletion: true
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: '{{.name}}-cluster-setup'
    spec:
      project: default
      source:
        repoURL: '{{index .metadata.annotations "uc_repo_git_url"}}'
        path: 'apps'
        targetRevision: '{{index .metadata.annotations "uc_repo_ref"}}'
      destination:
        server: '{{.server}}'
        namespace: argocd
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
