---
release_group: null

bootstrap:
  enabled: true
  ks_user: admin
  script: |
    # admin needs the admin role for the default domain
    openstack role add \
          --user="${OS_USERNAME}" \
          --domain="${OS_DEFAULT_DOMAIN}" \
          "admin"
    # TODO: only create this actually requested
    # create 'demo' user with sufficient permissions
    openstack user create --or-show --password demo --email 'demo@example.com' demo
    openstack user set --email 'demo@example.com' demo
    # add 'demo' user to 'ucadmin' group
    openstack group add user ucadmin demo
    # create 'argoworkflow' user
    # credentials for ironic-nautobot-sync and other argo workflows
    openstack project create undercloud --or-show
    openstack user create --project undercloud --password demo argoworkflow --or-show
    openstack role add --user argoworkflow --project undercloud member
    openstack role add --user argoworkflow --project undercloud admin
    # allow ironic user to see servers in undercloud project
    openstack role add --project undercloud --user ironic --user-domain service  member
    openstack role add --project service --user ironic --user-domain service service
    # add 'demo' user to have 'member' role, needed for horizon dashboard use
    openstack role add --user demo --project undercloud member

    # OIDC integration
    RULES_FILE=$(mktemp)
    cat <<EOF > ${RULES_FILE}
    [
        {
            "local": [
                {
                    "user": {
                        "id": "{0}",
                        "name": "{1}",
                        "email": "{2}"
                    },
                    "groups": "{3}",
                     "domain": {
                        "id": "default"
                    }
                }
            ],
            "remote": [
                {
                    "type": "HTTP_OIDC_SUB"
                },
                {
                    "type": "REMOTE_USER"
                },
                {
                    "type": "HTTP_OIDC_EMAIL"
                },
                {
                    "type": "HTTP_OIDC_GROUPS"
                }
            ]
        }
    ]
    EOF
    # look up or create our domain for SSO integration, called 'sso'
    sso_domain_id=$(openstack domain create --or-show --description "Domain for 'sso' identity provider" -f value -c id sso)

    # define our identity provider 'sso' for the domain 'sso'
    openstack identity provider show sso 2>/dev/null || openstack identity provider create --domain "${sso_domain_id}" --description "Identity Provider to our dex" --remote-id https://dex.dev.undercloud.rackspace.net sso

    # create or update the mapping that we'll use for the 'sso' identity
    if openstack mapping show sso_mapping 2>/dev/null; then
      openstack mapping set --rules ${RULES_FILE} sso_mapping;
    else
      openstack mapping create --rules ${RULES_FILE} sso_mapping;
    fi

    # clean up
    rm -f "${RULES_FILE}"

    # create the federation protocol 'openid' to use the identity provider 'sso' with the 'sso_mapping'
    openstack federation protocol show openid --identity-provider sso || openstack federation protocol create openid --mapping sso_mapping --identity-provider sso

    # create groups which map to our groups claim from dex which can be mapped to permissions
    for group in ucadmin ucuser ucneteng ucdctech; do
      openstack group create ${group} --or-show
      openstack role add --group ${group} --domain default member
    done
    openstack role add --group ucadmin --domain default admin
    openstack role add --group ucadmin --project undercloud admin

network:
  # configure OpenStack Helm to use Undercloud's ingress
  # instead of expecting the ingress controller provided
  # by OpenStack Helm
  use_external_ingress_controller: true

dependencies:
  static:
    db_sync:
      jobs:
        - keystone-credential-setup
        - keystone-fernet-setup

pod:
  resources:
    enabled: false
    api:
      requests:
        memory: "64Mi"
        cpu: "100m"
      limits:
        memory: "4096Mi"
    jobs:
      bootstrap:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      domain_manage:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      db_init:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      db_sync:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      db_drop:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      rabbit_init:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      tests:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      fernet_setup:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      fernet_rotate:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      credential_setup:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      credential_rotate:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      credential_cleanup:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
      image_repo_sync:
        requests:
          memory: "64Mi"
          cpu: "100m"
        limits:
          memory: "4096Mi"
  probes:
    api:
      api:
        readiness:
          enabled: true
          params:
            initialDelaySeconds: 15
            periodSeconds: 60
            timeoutSeconds: 15
        liveness:
          enabled: true
          params:
            initialDelaySeconds: 50
            periodSeconds: 60
            timeoutSeconds: 15
  mounts:
    keystone_api:
      keystone_api:
        volumeMounts:
          - name: keystone-sso
            mountPath: /etc/keystone-sso
            readOnly: true
        volumes:
          - name: keystone-sso
            secret:
              secretName: keystone-sso
  lifecycle:
    disruption_budget:
      api:
        min_available: 1

conf:
  keystone:
    auth:
      methods: password,token,openid,mapped,application_credential
    openid:
      remote_id_attribute: HTTP_OIDC_ISS
    federation:
      trusted_dashboard:
        type: multistring
        values:
          - http://localhost:9990/auth/websso/
          # - https://yourinstance.of.horizon.example.com/auth/websso/
    DEFAULT:
      max_token_size: 512
  wsgi_keystone: |
    {{- $portInt := tuple "identity" "service" "api" $ | include "helm-toolkit.endpoints.endpoint_port_lookup" }}

    Listen 0.0.0.0:{{ $portInt }}

    LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
    LogFormat "%{X-Forwarded-For}i %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" proxy

    SetEnvIf X-Forwarded-For "^.*\..*\..*\..*" forwarded
    CustomLog /dev/stdout combined env=!forwarded
    CustomLog /dev/stdout proxy env=forwarded
    ErrorLog /dev/stderr

    <VirtualHost *:{{ $portInt }}>
        WSGIDaemonProcess keystone-public processes=1 threads=1 user=keystone group=keystone display-name=%{GROUP}
        WSGIProcessGroup keystone-public
        WSGIScriptAlias / /var/www/cgi-bin/keystone/keystone-wsgi-public
        WSGIApplicationGroup %{GLOBAL}
        WSGIPassAuthorization On

        # OIDC
        OIDCClaimPrefix "OIDC-"
        OIDCRemoteUserClaim preferred_username ^(.*)@
        OIDCSessionType server-cache
        OIDCXForwardedHeaders X-Forwarded-Host X-Forwarded-Proto X-Forwarded-Port
        OIDCResponseType "code"
        OIDCScope "openid email profile groups"
        OIDCProviderMetadataURL http://dex.dex.svc:5556/.well-known/openid-configuration
        OIDCClientID keystone
        OIDCClientSecret "exec:/bin/cat /etc/keystone-sso/client-secret"
        OIDCCryptoPassphrase "exec:/bin/bash -c \"head /dev/urandom | tr -dc A-Za-z0-9 | head -c 32\""
        OIDCClaimDelimiter ;

        # avoid redirect issues per the following
        # https://review.opendev.org/c/openstack/keystone/+/925553
        OIDCRedirectURI https://{{- tuple "identity" "public" $ | include "helm-toolkit.endpoints.hostname_fqdn_endpoint_lookup" -}}/redirect_uri
        <Location ~ "/redirect_uri">
          Require valid-user
          AuthType openid-connect
        </Location>

        # add using the identity provider 'sso' with the protocol 'openid'
        <Location /v3/OS-FEDERATION/identity_providers/sso/protocols/openid/auth>
          Require valid-user
          AuthType openid-connect
        </Location>
        # websso support
        <Location /v3/auth/OS-FEDERATION/websso/openid>
          Require valid-user
          AuthType openid-connect
        </Location>
        <Location /v3/auth/OS-FEDERATION/identity_providers/sso/protocols/openid/websso>
          Require valid-user
          AuthType openid-connect
        </Location>
    </VirtualHost>


# typically overridden by environmental
# values, but should include all endpoints
# required by this chart
endpoints:
  oslo_messaging:
    statefulset:
      replicas: 3
      name: rabbitmq-server
    hosts:
      default: rabbitmq-nodes

manifests:
  job_credential_cleanup: false
  job_db_init: false
  job_rabbit_init: false
  pod_rally_test: false
  secret_db: false
  secret_keystone: true

# we don't want to enable OpenStack Helm's
# helm.sh/hooks because they set them as
# post-install,post-upgrade which in ArgoCD
# maps to PostSync. However the deployments
# and statefulsets in OpenStack Helm
# depend on the jobs to complete to become
# healthy. Which they cannot because they are in
# the post step and not in the main step.
# Turning this on results in the keys jobs
# editing the annotation which deletes the item
# and wipes our keys.
helm3_hook: false

annotations:
  job:
    keystone_fernet_setup:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    keystone_db_sync:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
    keystone_credential_setup:
      argocd.argoproj.io/hook: Sync
      argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
