---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: keystone-sso
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: dex
  target:
    name: keystone-sso
    creationPolicy: Owner
    deletionPolicy: Delete
  dataFrom:
    - extract:
        key: keystone-sso
