---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - keystone-mariadb-db.yaml
  - keystone-rabbitmq-queue.yaml

helmGlobals:
  chartHome: ../../charts/
helmCharts:
  - name: keystone
    namespace: openstack
    releaseName: keystone
    repo: https://tarballs.opendev.org/openstack/openstack-helm/
    version: 0.3.7
    valuesFile: aio-values.yaml
    additionalValuesFiles:
    - ../openstack-2023.1-jammy.yaml
    - ../../secret-openstack.yaml
