---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../charts/
helmCharts:
- name: memcached
  includeCRDs: true
  namespace: openstack
  valuesFile: values.yaml
  releaseName: memcached
  version: 6.7.1
  repo: https://charts.bitnami.com/bitnami
