---

bootstrap:
  image:
    enabled: false
    openstack:
      enabled: false
  network:
    enabled: false
    openstack:
      enabled: false
  object_store:
    enabled: false
    openstack:
      enabled: false

conf:
  ironic:
    conductor:
      automated_clean: false
    dhcp:
      dhcp_provider: none

network:
  api:
    ingress:
      public: true
      classes:
        namespace: "nginx"
        cluster: "nginx-openstack"
      annotations:
        nginx.ingress.kubernetes.io/rewrite-target: /
    external_policy_local: false
    node_port:
      enabled: false
  pxe:
    device: ens1f0

dependencies:
  dynamic:
    common:
      local_image_registry:
        jobs: null
  static:
    api:
      jobs:
        - ironic-db-sync
        - ironic-ks-user
        - ironic-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: oslo_messaging
    conductor:
      jobs:
        - ironic-db-sync
        - ironic-ks-user
        - ironic-ks-endpoints
      services:
        - endpoint: internal
          service: oslo_db
        - endpoint: internal
          service: oslo_messaging

manifests:
  job_db_init: false
  job_db_drop: false
  job_manage_cleaning_network: false
  job_rabbit_init: false
  secret_db: false
  secret_rabbitmq: false
  secret_registry: false
