apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: get-obm-creds
  namespace: argo-events
  annotations:
    workflows.argoproj.io/description: A placeholder template to return the name of a Kubernetes Secret which containing device's OBM credentials.
spec:
  serviceAccountName: workflow
  entrypoint: main
  arguments:
    parameters:
      - name: hostname
  templates:
    - name: main
      inputs:
        parameters:
          - name: hostname
      outputs:
        parameters:
          - name: secret
            value: "placeholder-obm-creds"
      container:
        image: ghcr.io/rackerlabs/understack/argo-utils-python3.11.8:latest
        command: [echo]
        args: ["*** PLACEHOLDER TEMPLATE. A WORKFLOW NEEDS TO BE CREATED TO RETURN THE NAME OF A SECRET CONTAINING CREDENTIALS. ***"]
