apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/rabbitmq/messaging-topology-operator/releases/download/v1.13.0/messaging-topology-operator-with-certmanager.yaml

patches:
- patch: |-
    apiVersion: v1
    kind: Namespace
    metadata:
      name: rabbitmq-system
    $patch: delete
