name: code tests

on:
  push:
    branches:
      - main
    paths:
      - "python/**"
      - ".github/workflows/code-test.yaml"
  pull_request:
    paths:
      - "python/**"
      - ".github/workflows/code-test.yaml"
  workflow_dispatch:

jobs:
  understack-workflows:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./python/understack-workflows

    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry==1.7.1 && poetry self add 'poetry-dynamic-versioning[plugin]'
      - uses: actions/setup-python@v5
        with:
          python-version-file: python/understack-workflows/pyproject.toml
          cache: "poetry"
      - run: poetry install --sync --with test
      - run: poetry build
      - run: "poetry run pytest --cov-report xml:coverage.xml"
      - uses: orgoro/coverage@v3.2
        with:
          coverageFile: python/understack-workflows/coverage.xml
          token: ${{ secrets.GITHUB_TOKEN }}
